module.exports = {
    column:"fruit vegetable spice".split(" "),
    fruit:["Acai Berries",
           "Aronia",
           "Bilberry",
           "Blackberries",
           "Blueberries",
           "Camu Camu",
           "Chinese Bayberry",
           "Cranberry",
           "Guavaberries",
           "Gogi Berries",
           "Gooseberries",
           "Raspberries",
           "Strawberries",
           "Berries List",
           "Apples",
           "Apricots",
           "Banana",
           "Cantaloupe",
           "Cherries",
           "Clementines",
           "Date Palm",
           "Grapefruit",
           "Green Grapes",
           "Honeydew Melon",
           "Lemons",
           "Limes",
           "Mandarin Oranges",
           "Mangos",
           "Oranges",
           "Papayas",
           "Peaches",
           "Pears",
           "Pineapple",
           "Plantain",
           "Plums",
           "Pomelo",
           "Red Grapes",
           "Tangerine",
           "Watermelon",
           "Common fruit list",
           "Acerola",
           "Coconut",
           "Guava",
           "Guinep",
           "Hog Apple",
           "Horned Melon",
           "Jackfruit",
           "Kiwi Fruit",
           "Kumquat",
           "Lychee",
           "Mangosteen",
           "Noni",
           "Passion Fruit",
           "Peanut Butter Fruit",
           "Pomegranate",
           "Prickly Pear",
           "Soursop",
           "Star Apple",
           "Tamarind"],
    "vegetable":["Acorn Squash",
                 "Ahipa",
                 "Amaranth",
                 "American Groundnut",
                 "Aonori",
                 "Arame",
                 "Arracacha",
                 "Arrowroot",
                 "Artichoke",
                 "Arugula",
                 "Asparagus",
                 "Adzuki Bean",
                 "Bamboo Shoots",
                 "Banana Squash",
                 "Beetroot",
                 "Belgian Endive",
                 "Bell Peppers",
                 "Black Eyed Pea",
                 "Black Radish",
                 "Black Salsify",
                 "Bok Choy",
                 "Broadleaf Arrowhead",
                 "Broccoflower",
                 "Broccoli",
                 "Broccolini",
                 "Brussel Sprouts",
                 "Burdock Roots",
                 "Buttercup Squash",
                 "Butternut Squash",
                 "Cabbage",
                 "Cactus",
                 "Camas",
                 "Canna",
                 "Caper",
                 "Cardoon",
                 "Carrot",
                 "Cassava",
                 "Catsear",
                 "Cauliflower",
                 "Celeriac",
                 "Celery",
                 "Celtuce",
                 "Chaya",
                 "Chayote Squash",
                 "Cherry Tomato",
                 "Chick Pea",
                 "Chickweed",
                 "Chicory",
                 "Chives",
                 "Chrysanthemum",
                 "Collard Greens",
                 "Common Beans",
                 "Crookneck Squash",
                 "Common Purslane",
                 "Courgette Flowers",
                 "Cress",
                 "Cucumbers",
                 "Dabberlocks",
                 "Daikon",
                 "Dandelion",
                 "Delicata Squash",
                 "Daylily",
                 "Dill",
                 "Dolichos",
                 "Drumstick",
                 "Dulse",
                 "Earthnut Pea",
                 "Eggplant",
                 "Elephant Foot Yam",
                 "Elephant Garlic",
                 "Endive",
                 "Ensete",
                 "Fat Hen",
                 "Fava bean",
                 "Fennel",
                 "Fiddlehead Green",
                 "Florence Fennel",
                 "Fluted Pumpkin",
                 "Galangal",
                 "Garbanzo",
                 "Garden Rocket",
                 "Garlic",
                 "Garlic Chives",
                 "Ginger",
                 "Golden Samphire",
                 "Good King Henry",
                 "Greater Plantain",
                 "Green Beans",
                 "Green Soybeans",
                 "Guar",
                 "Hamburg Parsley",
                 "Hijiki",
                 "Horse Gram",
                 "Horseradish",
                 "Indian Pea",
                 "Kale",
                 "Kohlrabi",
                 "Komatsuna",
                 "Kombu",
                 "Kurrat",
                 "Lagos Bologi",
                 "Land Cress",
                 "Laver",
                 "Leek",
                 "Lemongrass",
                 "Lentil",
                 "Lettuce",
                 "Lima Bean",
                 "Lotus Root",
                 "Malabar Spinach",
                 "Mangetout",
                 "Manoa",
                 "Mashua",
                 "Mulukhiyah",
                 "Mizuna",
                 "Morel Mushrooms",
                 "Moth Bean",
                 "Mozuku",
                 "Mung Bean",
                 "Mushrooms",
                 "Mustard Greens",
                 "Napa Cabbage",
                 "New Zealand Spinach",
                 "Nopal",
                 "Nori",
                 "Ogonori",
                 "Okra",
                 "Onion",
                 "Orache",
                 "Pak Choy",
                 "Paracress",
                 "Parsnip",
                 "Peas",
                 "Pearl Onion",
                 "Pigeon Pea",
                 "Pignut",
                 "Potato",
                 "Prussian Asparagus",
                 "Prairie Turnip",
                 "Pumpkin",
                 "Radicchio",
                 "Radish",
                 "Ramp",
                 "Rapini",
                 "Red Leaf Lettuce",
                 "Ricebean",
                 "Runner Bean",
                 "Rutabaga",
                 "Salad Savoy",
                 "Salsify",
                 "Samphire",
                 "Scorzonera",
                 "Sculpit",
                 "Sea Beet",
                 "Sea Grape",
                 "Sea Kale",
                 "Sea Lettuce",
                 "Shallot",
                 "Sierra Leone Bologi",
                 "Skirret",
                 "Snap Pea",
                 "Snow Pea",
                 "Soko",
                 "Sorrel",
                 "Sour Cabbage",
                 "Soybean",
                 "Spinach",
                 "Spring Onion",
                 "Scallion",
                 "Squash Blossoms",
                 "Summer Squash",
                 "Swede",
                 "Sweet Potato",
                 "Taro",
                 "Tarwi",
                 "Tatsoi",
                 "Tepary Bean",
                 "Tigernut",
                 "Tomatillo",
                 "Tomato",
                 "Tree Onion",
                 "Turmeric",
                 "Turnip",
                 "Urad Bean",
                 "Ulluco",
                 "Wasabi",
                 "Water Chestnut",
                 "Water Caltrop",
                 "Water Spinach",
                 "Watercress",
                 "Welsh Onion",
                 "Wheatgrass",
                 "Wild Leek",
                 "Winged Bean",
                 "Winter Squash",
                 "Yam",
                 "Yao Choy",
                 "Yardlong Bean",
                 "Yarrow",
                 "Yuca Root",
                 "Yukon Gold Potatoes",
                 "Zucchini"],
    "spice":["cardamom",
             "clove",
             "cassia bark",
             "black pepper",
             "celery seed",
             "coriander seed",
             "crushed red pepper",
             "cumin",
             "curry powder",
             "nutmeg",
             "mace",
             "mustard seeds",
             "garlic",
             "ginger",
             "turmeric",
             "fenugreek",
             "saffron",
             "allspice",
             "anise",
             "caraway seed",
             "carom ",
             "cayenne",
             "chili pepper",
             "fennel",
             "paprika",
             "sumac",
             "cinnamon",
             "onion powder",
             "galangal root powder",
             "star anise",
             "black cumin",
             "poppy seeds",
             "pumpkin spice"]
}
